### ISSUE TITLE
Do you need to override my 404 handler?

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#13]
My app has a 404 handler in the form of the error function signature, but 404 errors don't get to it. I don't like that. Does it have to be that way?

**Comment by ryanburnette** [comment]
404 errors like `curl localhost:3000/api/authn/foo` for example

**Comment by coolaj86** [comment]
A 404 handler is not an error handler. It would be a normal “moddleware” as a catch all after all other middleware.

**Comment by ryanburnette** [comment]
Does auth3000 need to handle 404? Don’t think it does.

**Comment by ryanburnette** [comment]
Yea it was a stupid request I guess.
