### ISSUE TITLE
inconsistent with passing keypair to sessionMiddleware and authnMiddleware

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#19]
sessionMiddlware expects keypair as JSON

authnMiddleware expects keypair as obj

will this be more consistent in a future release?

aside: I prefer passing opts as attributes of opts object rather than setting them in the env

**Comment by coolaj86** [comment]
Object is allowed in both places.

**Comment by coolaj86** [comment]
Can you give a code sample?

**Comment by ryanburnette** [comment]
Am I doing this wrong?

This is a sample from my app that I'm currently developing. I noticed that one I just passed the raw string, other I had to run `JSON.parse` to make it happy. I might be passing the wrong key entirely.

```js
// app.js
var KEYPAIR = require('fs').readFileSync('.keypair.json', 'utf8');
var authnProvider = require('auth3000/lib/session')({
  iss: BASE_URL,
  keypair: KEYPAIR,
  // ...
})

var authnMiddleware = require('auth3000/lib/middleware')({
  iss: BASE_URL,
  pub: JSON.parse(KEYPAIR),
  strict: true
});
```

**Comment by coolaj86** [comment]
`pub` is optional and, if provided, should be _only_ the public key, not the keypair.

`pub` is only required if the `wellKnown` middleware is not loaded.
