### ISSUE TITLE
Error handler

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#21]
This is a http api, so I propose that included error handling should be as minimalistic as possible.

- Provide minimalistic error handling out of the box
- Allow the user to override it
- Allow the user to reliably react to it

For me, I'd like to be able to pass `{ errorHandler }` during initialization and pass...

```js
function errorHandler(err, req, res, next) {
    next(err);
}
```

...so I can use my global error handler.

Thoughts?

**Comment by ryanburnette** [comment]
Also, having a reliable and documented list of all the errors and what they mean could help the implementer to handle them as desired. Maybe like

```js
if (err._auth3000) {
}
```

Or because there is a reliable list of the messages they return.

Having `.code` or `.status` on the error objects forces users into a pattern that, while it might be great, isn't something you should impose on others.

**Comment by coolaj86** [comment]
I don't know what you mean. You can do your error handling however you want. There's no restriction on you from the library.

**Comment by coolaj86** [comment]
While this is in development the list of error codes is:

```bash
rg err.code ./
```

Agreed it should be in the README / docs once things are further along.

**Comment by ryanburnette** [comment]
I'm not sure what was happening that caused me to think I wasn't able to handle all the errors. If I run across it again I'll open a new issue.

My APIs generally have a global error handler with some logic like this...

```js
function (err, req, res, next) {
  if (err.name === 'SequelizeUniqueConstraintError') {
  }
  if (err.code === 'INVALID_AUTH') {
  }
}
```

...where I handle responses for errors from various libraries further down the stack. Using `err.code` seems like a fine way, and documentation about such will allow implementers to reveal as much or as little about what's happening in auth3000 as they like.

Looking good.

**Comment by coolaj86** [comment]
Errors moved to `lib/errors.js`, will be added to the README too.

**Comment by coolaj86** [comment]
This was done.
