### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#22]
I propose that timeouts can be set during initialization, but have sensible defaults.

**Comment by coolaj86** [comment]
You mean expiry for tokens? Agreed.

**Comment by coolaj86** [comment]
I think we should discuss this.

I don't have a good solution top of mind, but I think if we both looked at it we'd come up with the right thing.

Maybe `getUser` should actually be more like:

- `session.byOidc()` // google sign in
- `session.byCredentials()` // password
- `session.byCookie()` // refresh cookie
- `session.byToken()` // exchange short-lived token for another token
- `session.byIdentifierVerification()` // magic link

In any case, there are two values that need to be set - how long the refresh cookie should last (ex: 30 days) and how long the short-lived token should last (ex: 15m).

**Comment by ryanburnette** [comment]
> You mean expiry for tokens? Agreed.

Yes

**Comment by coolaj86** [comment]
closing in favor of https://github.com/therootcompany/auth3000/issues/11
